[profile.default] # all profiles inherit from this
solc = '0.8.13' 
src = 'contracts'
out = 'out' # default
test = 'test' # default
libs = ['lib', 'node_modules']
cache = false # !important! breaks echidna if cache = true.
remappings = [
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/',
    'solstat/=lib/solstat/contracts/',
    'contracts/=contracts/',
    'lib/=lib/'
]

[profile.optimized] # uses via_ir and optimizer
via_ir = true
out = 'optimized-out'
optimizer_runs = 15000
fuzz_runs = 256
fuzz_max_local_rejects = 65536
fuzz_max_global_rejects = 1024

[profile.test] # does not use optimizer
src = 'test/' # not default
gas_reports = ["*"]
ffi = true
fuzz_runs = 1000

[profile.crytic]
via_ir = false
src = 'test/crytic' # not default
test = 'test/crytic' # not default


[rpc_endpoints]
primitive = "http://${PRIMITIVE_RPC}:8545"


# See more config options https://github.com/gakonst/foundry/tree/master/config
