[profile.default]
solc = '0.8.13'
via_ir = true
src = 'contracts'
out = 'artifacts/contracts'
libs = ['lib', 'node_modules']
test = 'test/foundry'
remappings = [
    'ds-test/=lib/solmate/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/',
    'solstat/=lib/solstat/contracts/',
    'contracts/=contracts/',
    'lib/=lib/'
]
cache = false
optimizer_runs = 15000
fuzz_runs = 256
fuzz_max_local_rejects = 65536
fuzz_max_global_rejects = 1024

[profile.optimized]
solc = '0.8.13'
out = 'optimized-out'

[profile.test]
cache = false
solc = '0.8.13'
via_ir = false
src = 'test/'
out = 'artifacts/contracts'
libs = ['lib', 'node_modules']
gas_reports = ["*"]
ffi = true
fuzz_runs = 500

[profile.lite]
cache = false
out = 'optimized-out'
via_ir = false
fuzz_runs = 1000

[profile.crytic]
solc = '0.8.13'
cache = false
via_ir = false
libs = ['lib', 'node_modules']
src = 'test/crytic'
test = 'test/crytic'
out = 'out'

[rpc_endpoints]
primitive = "http://${PRIMITIVE_RPC}:8545"


# See more config options https://github.com/gakonst/foundry/tree/master/config
